### ISSUE TITLE
Help wanted - UI-wise!

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [Thomas-A-Reinert/WordPress-Developer-Checklist#5]
It works. But I´m not a designer nor am I really, really comfi with the UI right now. 
Nothing more, nothing less. It does the job.

Which doesn´t mean, the UX cannot be improved. If UI/UX development is you main concern and you meet any improvable use-cases - PLEASE HOLLA!

**Comment by alokpant** [comment]
Hey, if this is still open, I would love to take this on. If you have list of things that need to be tackled, would be great if you can share it with me.

**Comment by Thomas-A-Reinert** [comment]
@alokpant - Yes, this issue is still on the todo-list. I´m really open for any improvements!

I just currently don´t find the time to update the list as i´m heavily involved into some other commercial projects that need to pay the bills ;)
